imports:
    - { resource: "../../config/parameters.yml" }
    - { resource: "../../config/config.yml" }
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: fos_oauth_server.yml }
    
# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
