imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: validator.mapping.cache.apc
#    serializer:
#        cache: serializer.mapping.cache.apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console

swiftmailer:
    mailers:
      default:
        disable_delivery: false
        spool: { type: file, path: %kernel.root_dir%/spool }
      account:
        disable_delivery: false
        spool: { type: file, path: %kernel.root_dir%/spool }
      verification:
        disable_delivery: false
        spool: { type: file, path: %kernel.root_dir%/spool }
      transaction:
        disable_delivery: false
        spool: { type: file, path: %kernel.root_dir%/spool }