<?php

namespace App\Bundle\CoreBundle\Repository\Yilinker;

/**
 * BrandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandRepository extends \Doctrine\ORM\EntityRepository
{

    public function findOne($id)
    {
   
        $user = $this->createQueryBuilder('b')
                    ->where('b.brandId = :id')
                    ->setParameter('id', $id)
                    ->getQuery()
                    ->getResult();
        
        return $user;
    } 
}
