<?php

namespace App\Bundle\CoreBundle\Repository;

/**
 * InventoryRoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InventoryRoomRepository extends \Doctrine\ORM\EntityRepository
{
}
