<?php

namespace App\Bundle\CoreBundle\Repository;

/**
 * LabLogItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LabLogItemRepository extends \Doctrine\ORM\EntityRepository
{
}
