<?php

namespace App\Bundle\CoreBundle\Repository;

/**
 * UserImage
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserImage extends \Doctrine\ORM\EntityRepository
{
}
