<?php

namespace App\Bundle\CoreBundle\Repository;

/**
 * YiProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YiProductRepository extends \Doctrine\ORM\EntityRepository
{
}
