<?php

namespace App\Bundle\CoreBundle\Repository;

/**
 * YiUser
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YiUserRepository extends BaseQueryRepository
{

    public function findUserByEmailExcludeId($params)
    {
        $this->qb()
            ->select(array('this'));
        
        $this->criteriaForEmailExcludeId($params);

        return $this->getCount();
    }

    public function countEmail($email)
    {
        $this->qb()->criteriaEmail($email);

        return $this->getCount();
    }
    
    public function criteriaForEmailExcludeId($params)
    {
        extract($params);

        $this
            ->andWhere("this.userId <> :id")
            ->setParameter('id',$id)
            ->criteriaEmail($email);
            
        return $this;
    }


    public function criteriaEmail($email)
    {
        $this
            ->andWhere("this.email = :email")
            ->setParameter("email", $email);

        return $this;

    }
}
