App\Bundle\CoreBundle\Entity\Country:
    type: entity
    table: Country
    repositoryClass: App\Bundle\CoreBundle\Repository\Country
    uniqueConstraints:
        UNIQ_9CCEF0FA5E237E06:
            columns:
                - name
    id:
        countryId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: country_id
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        code:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
        dateAdded:
            type: datetime
            nullable: false
            column: date_added
        dateLastModified:
            type: datetime
            nullable: false
            column: date_last_modified
        referenceNumber:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: reference_number
        areaCode:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
            column: area_code
    lifecycleCallbacks: {  }
