App\Bundle\CoreBundle\Entity\Employee:
    type: entity
    fields:
        job:
            type: string
            nullable: false
        company:
            type: string
            column: company
