App\Bundle\CoreBundle\Entity\InventoryRoom:
    type: entity
    table: inventory_room
    repositoryClass: App\Bundle\CoreBundle\Repository\InventoryRoomRepository
    fields:
        roomType:
            type: string
            column: room_type
        rackLimit:
            length: 255
            options:
                default: ''
