App\Bundle\CoreBundle\Entity\OauthAccessToken:
    type: entity
    table: OauthAccessToken
    id:
        id:
            type: integer
            id: true
            unsigned: false 
            generator:
                strategy: AUTO
    manyToOne:
        client:
            targetEntity: OauthClient
            joinColumn: 
                name: client_id
                referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: User
            joinColumn:
                name: user_id
                referencedColumnName: user_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
