App\Bundle\CoreBundle\Entity\Userimage:
    type: entity
    table: UserImage
    repositoryClass: App\Bundle\CoreBundle\Repository\UserImage
    indexes:
        IDX_A1A9952AA76ED395:
            columns:
                - user_id
    id:
        userImageId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: user_image_id
            generator:
                strategy: IDENTITY
    fields:
        userId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: user_id
        imageLocation:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                default: ''
            column: image_location
        isHidden:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: is_hidden
        dateAdded:
            type: datetime
            nullable: false
            column: date_added
        userImageType:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
            column: user_image_type
    lifecycleCallbacks: {  }
