App\Bundle\CoreBundle\Entity\YiProductwarehouse:
    type: entity
    table: yi_productwarehouse
    repositoryClass: App\Bundle\CoreBundle\Repository\YiProductwarehouseRepository
    indexes:
        user_warehouse_id:
            columns:
                - user_warehouse_id
        product_id:
            columns:
                - product_id
    id:
        productWarehouseId:
            type: bigint
            nullable: false
            options:
                unsigned: true
            id: true
            column: product_warehouse_id
            generator:
                strategy: IDENTITY
    fields:
        priority:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '1'
        countryCode:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
                default: ph
            column: country_code
        dateAdded:
            type: datetime
            nullable: false
            column: date_added
        logisticsId:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '1'
            column: logistics_id
        isCod:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: is_cod
        handlingFee:
            type: decimal
            nullable: false
            precision: 12
            scale: 4
            options:
                default: '0.0000'
            column: handling_fee
    manyToOne:
        userWarehouse:
            targetEntity: YiUserwarehouse
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: yiProductwarehouses
            joinColumns:
                user_warehouse_id:
                    referencedColumnName: user_warehouse_id
            orphanRemoval: false
        product:
            targetEntity: YiProduct
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: yiProductwarehouses
            joinColumns:
                product_id:
                    referencedColumnName: product_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
